
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "password123?"
    ports:
      - "1433:1433"
    volumes:
      - ./adw_oltp_data:/adw_oltp_data
      - ./scripts:/scripts
      - ./entrypoint.sh:/entrypoint.sh
    command: ["/bin/bash", "/entrypoint.sh"]


